// ENV
require('dotenv').config();

const {
  NODE_ENV, PORT, TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET, TWITTER_ACCESS_TOKEN,
  TWITTER_ACCESS_SECRET, GOOGLE_MAPS_API_KEY, GOOGLE_PLACES_API_KEY,
} = process.env;

let RABBITMQ_CONNECT;

switch (NODE_ENV) {
  case 'PRODUCTION':
    RABBITMQ_CONNECT = process.env.RABBITMQ_SERVER_ID_PROD;
    break;
  case 'DEVELOPMENT_LOCAL':
    RABBITMQ_CONNECT = process.env.RABBITMQ_SERVER_ID_LOCAL;
    break;
  case 'TEST_LOCAL':
    RABBITMQ_CONNECT = process.env.RABBITMQ_SERVER_ID_LOCAL;
    break;
  case 'DEVELOPMENT_DOCKER':
    RABBITMQ_CONNECT = process.env.RABBITMQ_SERVER_ID_DOCKER;
    break;
  case 'TEST_DOCKER':
    RABBITMQ_CONNECT = process.env.RABBITMQ_SERVER_ID_DOCKER;
    break;
  default:
}

module.exports = {
  NODE_ENV,
  PORT,
  TWITTER_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET,
  TWITTER_ACCESS_TOKEN,
  TWITTER_ACCESS_SECRET,
  GOOGLE_MAPS_API_KEY,
  GOOGLE_PLACES_API_KEY,
  RABBITMQ_CONNECT,
};
