version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'
  redis:
    container_name: redis
    image: 'redis:4.0.11'
    ports: 
      - '6379:6379'
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq'
    ports: 
      - '5672:5672'
  app-service-vendor:
    container_name: docker-rollio-service-vendor
    build: .
    env_file:
      - .env
    environment:
      - NODE_ENV=DEVELOPMENT_DOCKER
    restart: always
    ports: 
      - '80:3001'
    links:
      - redis
      - mongo
      - rabbitmq