// DATA ACTIONS
export const FETCH_REGION_DATA = 'FETCH_REGION_DATA'
export const FETCH_REGION_DATA_SUCCESS = 'FETCH_REGION_DATA_SUCCESS'
export const RECIEVE_REGION_DATA = 'RECIEVE_REGION_DATA'

export const FETCH_VENDOR_DATA = 'FETCH_VENDOR_DATA'
export const FETCH_VENDOR_DATA_SUCCESS = 'FETCH_VENDOR_DATA_SUCCESS'
export const RECIEVE_VENDOR_DATA = 'RECIEVE_VENDOR_DATA'

export const FETCH_ALL_VENDORS = 'FETCH_ALL_VENDORS'
export const FETCH_ALL_VENDORS_SUCCESS = 'FETCH_ALL_VENDORS_SUCCESS'
export const RECIEVE_ALL_VENDORS = 'RECIEVE_ALL_VENDORS'

export const CLEAR_SELECTED_VENDOR = 'CLEAR_SELECTED_VENDOR'

export const FETCH_ALL_REGIONS = 'FETCH_ALL_REGIONS'
export const FETCH_ALL_REGIONS_SUCCESS = 'FETCH_ALL_REGIONS_SUCCESS'
export const RECEIVE_ALL_REGIONS = 'RECEIVE_ALL_REGIONS'

export const SET_VENDORS_ALL = 'SET_VENDORS_ALL'

export const UPDATE_VENDOR = 'UPDATE_VENDOR'

export const POST_VENDOR_COMMENT = 'POST_VENDOR_COMMENT'

// MAP ACTIONS
export const SET_MAP_PINS = 'SET_MAP_PINS'

export const SET_MAP_PIN_LOAD_STATE = 'SET_MAP_PIN_LOAD_STATE'

export const SET_VENDORS_DISPLAYED_SINGLE = 'SET_VENDORS_DISPLAYED_SINGLE'

export const SET_VENDORS_DISPLAYED_GROUP = 'SET_VENDORS_DISPLAYED_GROUP'

export const SET_REGION_MAP_VENDOR = 'SET_REGION_MAP_VENDOR'

export const SET_PREVIOUSLY_SELECTED_REGION_MAP = 'SET_PREVIOUSLY_SELECTED_REGION_MAP'

export const SET_CURRENTLY_SELECTED_REGION_MAP = 'SET_CURRENTLY_SELECTED_REGION_MAP'

// USER ACTIONS
export const RECEIVE_USER = 'RECEIVE_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCESS'
export const FETCH_USER = 'FETCH_USER'

export const LOG_OUT = 'LOG_OUT'

// UI ACTIONS
export const TOGGLE_MOBILE_DASHBOARD = 'TOGGLE_MOBILE_DASHBOARD'
export const TOGGLE_MAIN_DROPDOWN_MENU = 'TOGGLE_MAIN_DROPDOWN_MENU'
export const SET_IS_VENDOR_SELECTED = 'SET_IS_VENDOR_SELECTED'
export const SET_DASHBOARD_VENDORS_DISPLAY = 'SET_DASHBOARD_VENDORS_DISPLAY'
