// DATA ACTIONS
export const FETCH_REGION_DATA = 'FETCH_REGION_DATA'
export const FETCH_REGION_DATA_SUCCESS = 'FETCH_REGION_DATA_SUCCESS'
export const RECIEVE_REGION_DATA = 'RECIEVE_REGION_DATA'

export const FETCH_VENDOR_DATA = 'FETCH_VENDOR_DATA'
export const FETCH_VENDOR_DATA_SUCCESS = 'FETCH_VENDOR_DATA_SUCCESS'
export const RECIEVE_VENDOR_DATA = 'RECIEVE_VENDOR_DATA'

export const FETCH_ALL_VENDORS = 'FETCH_ALL_VENDORS'
export const FETCH_ALL_VENDORS_SUCCESS = 'FETCH_ALL_VENDORS_SUCCESS'
export const RECIEVE_ALL_VENDORS = 'RECIEVE_ALL_VENDORS'

export const POST_VENDOR_COMMENT = 'POST_VENDOR_COMMENT'

// MAP ACTIONS
export const SET_MAP_PINS = 'SET_MAP_PINS'

export const SET_MAP_PIN_LOAD_STATE = 'SET_MAP_PIN_LOAD_STATE'