# Category
cat = {
    'ADD': 'ADDRESS',
    'HT': 'HASHTAG',
    'NBR': 'NEIGHBORHOOD',
    'NULL': 'NULL'
}

# Time
t = {
    'TOD': 'TODAY',
    'TMRW': 'TOMORROW',
    'DT': 'DATE',
    'TIME': 'TIME',
    'NULL': 'NULL'
}

# Affirmation
aff = {
    'POS': 'POSITIVE',
    'NEG': 'NEGATIVE',
    'NULL': 'NULL'
}

# Training Data
train_data = [
("'This is my f**king country': Racist white woman arrested for attacking passengers on New York bus https://t.co/Rfm0jauh72", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @mussie671: Freestyle #3, Fiasco type shiiii https://t.co/0GTJscWORW", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("What you think Cole? @JColeNC @JColeDirect https://t.co/oE4Ipvq6hL", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("⚡️ “Redskins dominate the Raiders on Sunday Night Football ”https://t.co/4VuHWOs1gX", {'category': [(cat['NULL'], [])], 'time': [(t['DT'], [37,49])], 'affirmation': [(aff['NULL'], [])] }),
("RT @NWSSanJuan: 215PM FLASH FLOOD EMERGENCY for A Dam Failure in Isabela Municipality y Quebradillas Municipality in Puerto Rico... #prwx h…", {'category': [(cat['NBR'], [65,85]), (cat['NBR'], [88,113])], 'time': [(t['TIME'], [16,21])], 'affirmation': [(aff['NULL'], [])] }),
("Posted @chinatown on the corner of 7th &amp; D st. NW, PERFECT WEATHER TO SLIDE UP!!", {'category': [(cat['ADD'], [35,53])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [0,34])] }),
("Good Morning DMV, we are @ChinaTown on the corner of 7th &amp; G st NW. Hand crafted burgers, endless toppings, Hand cut fries,  PULL UP !!!", {'category': [(cat['ADD'], [53,70])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [18,52])] }),
("Good Morning DMV, we are @ChinaTown on the corner of 7th &amp; G st. NW serving our delicious hand crafted burgers and Home made fries. PULL UP!", {'category': [(cat['ADD'], [53,71])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [18,52])] }),
("Good morning angry burger lovers, we are back in China town, 7th &amp; G st. NW serving our delicious hand crafted burgers and home made fries!!", {'category': [(cat['ADD'], [61,79])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [34,59])] }),
("Good Morning Angry burger lovers, we are serving @Chinatown on the corner of 7th and G st NW. See you there!", {'category': [(cat['ADD'], [77,92])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [34,76])] }),
("Good morning DMV we are @ChinaTown today, on the corner of 7th and F st NW. COME EAT ‘EM UP!!!", {'category': [(cat['ADD'], [59,74])], 'time': [(t['TOD'], [34,40])], 'affirmation': [(aff['POS'], [17,58])] }),
("Good morning angry burger lovers, we are serving on the corner of 25th &amp; M today, see you there!", {'category': [(cat['ADD'], [66,78])], 'time': [(t['TOD'], [79,84])], 'affirmation': [(aff['POS'], [34,65])] }),
("Good morning DMV, we are serving lunch China town on the corner of 7th &amp; D st NW. Come get you some!!", {'category': [(cat['ADD'], [39,49]), (cat['ADD'], [67,84])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [18,66])] }),
("Good morning angry burger lovers, we are @L’enfant plaza serving our delicious burgers and hand cut fries! See you there!", {'category': [(cat['ADD'], [42,56])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [34, 86])] }),
("Good morning DMV, we will be on the cornor of 19th &amp; L st. NW serving our delicious hand crafted burgers and hand cut fries. SEE YOU THERE!", {'category': [(cat['ADD'], [46,65])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [18,45])] }),
("Good morning DMV, We are on the corner of 25th &amp; M st NW kicking out our delicious burgers, BMF’s and hand cut fries! Come get you some!!", {'category': [(cat['ADD'], [42,60])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [18,41])] }),
("Good morning DMV, We will be serving @ 25th &amp; M today. See ya there!", {'category': [(cat['ADD'], [39,51])], 'time': [(t['TOD'], [52,57])], 'affirmation': [(aff['POS'], [18,36])] }),
("Good morning DMV, it’s a beautiful day, we’ll be @Chinatown on the corner of 7th &amp; G st. Serving our delicious burgers and hand cut fries!!", {'category': [(cat['ADD'], [77,91])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [40,76])] }),
("Come enjoy lunch with us at Virginia Ave and 20th st NW from 11am to 2pm 😋 see you soon! #arepas #patacones… https://t.co/F3BQPKzWNf", {'category': [(cat['ADD'], [28,55])], 'time': [(t['TIME'], [61,72])], 'affirmation': [(aff['POS'], [0,27])] }),
("Happy humpday!! Find us at Farragut square from 11:30am to 2pm! 🤗 see you soon! #arepas #patacones #venezuelanfood… https://t.co/IENRYU3X0I", {'category': [(cat['ADD'], [27,42])], 'time': [(t['TIME'], [48,62])], 'affirmation': [(aff['POS'], [16,26])] }),
("Happy Friday!!! Come join us for lunch today at 20 Massachusetts Ave by Union Station from 11:30am to 2pm. See you… https://t.co/mb0RzawFgm", {'category': [(cat['ADD'], [48,68]), (cat['NBR'], [72,85])], 'time': [(t['TOD'], [39,44]), (t['TIME'],[91,105])], 'affirmation': [(aff['POS'], [16,47])] }),
("Happy Friday!! Cone have lunch with us by 20 Massachusetts Ave. close by Union Station. Window open from 11am to 1:… https://t.co/rPOxYH2h32", {'category': [(cat['ADD'], [42,62]), (cat['NBR'],[73,86])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [15,41])] }),
("Happy humpday! Have lunch with us today at Farragut Square from 11am to 1:30pm. See you at lunchtime 😋 #arepas… https://t.co/1aGfOUvRJN", {'category': [(cat['NBR'], [43,58])], 'time': [(t['TIME'], [64,78])], 'affirmation': [(aff['POS'], [15,42])] }),
("Happy Friday! 🤗 come have lunch with us! today we are by 20 Massachusetts Ave. one block from Union Station. Will b… https://t.co/i9WpS2a3qp", {'category': [(cat['ADD'], [57,77]), (cat['NBR'], [94,107])], 'time': [(t['TOD'], [41,46])], 'affirmation': [(aff['POS'], [41,56])] }),
("Happy humpday!! Have lunch with us today at Farragut Sq on 17th St NW from 11am to 2pm 🤤 see you at lunchtime!… https://t.co/uD8N5dv0c3", {'category': [(cat['NBR'], [44,55]), (cat['ADD'], [59,69])], 'time': [(t['TOD'], [35,40]),(t['TIME'], [75,86])], 'affirmation': [(aff['POS'], [16,43])] }),
("Come have lunch with us today at L St and 18th St NW from 11am to 2pm. 😋 #arepas #patacones #venezuelanfood… https://t.co/iAYU60TBW2", {'category': [(cat['ADD'], [33,52])], 'time': [(t['TIME'], [58,69])], 'affirmation': [(aff['POS'], [0,32])] }),
("Happy Friday! Come have lunch with us at Virginia Ave and 20th St NW from 11:30am to 2pm. 🤤 #arepas #patacones… https://t.co/AgbiimSwmG", {'category': [(cat['ADD'], [41,68])], 'time': [(t['TIME'], [74,88])], 'affirmation': [(aff['POS'], [14,40])] }),
("Find us by Union Station today from 11am to 1:30pm! See you at lunchtime! 🤗 #arepas #patacones #cachapas… https://t.co/m0RnNakUfN", {'category': [(cat['NBR'], [11,24])], 'time': [(t['TOD'], [25,30]), (t['TIME'], [36,50])], 'affirmation': [(aff['POS'], [0,10])] }),
("Happy humpday! We are at L St and 18th St NW from 11am to 2pm. 😋 see you soon! #arepas #patacones #venezuelanfood… https://t.co/zdqlNAdmHx", {'category': [(cat['ADD'], [25,44])], 'time': [(t['TIME'], [50,61])], 'affirmation': [(aff['POS'], [15,24])] }),
("Come have lunch with us at L’Enfant Plaza Station from 11:30am to 2pm. 🤤 #arepas #patacones #venezuelanfood… https://t.co/ncYg97TWhn", {'category': [(cat['NBR'], [27,49])], 'time': [(t['TIME'], [55,69])], 'affirmation': [(aff['POS'], [0,26])] }),
("Happy Friday! Find us at L St and 19th St NW from 11:30 am to 2pm. #arepas #patacones #venezuelanfood #foodtruck… https://t.co/mHSgLR8vFD", {'category': [(cat['ADD'], [25,44])], 'time': [(t['TIME'], [50,65])], 'affirmation': [(aff['POS'], [14,24])] }),
("Come find us by Union Station from 11:30am to 2pm. See you at lunchtime 🤤 #arepas #patacones #venezuelanfood… https://t.co/mgtXfhQF9z", {'category': [(cat['NBR'], [16,29])], 'time': [(t['TIME'], [35,49])], 'affirmation': [(aff['POS'], [0,15])] }),
("Happy Friday! We are at Virginia Ave and 20th St NW from 11am to 2pm. See you soon 😋 #arepas #patacones… https://t.co/rdiOS2M8FD", {'category': [(cat['ADD'], [24,51])], 'time': [(t['TIME'], [57,68])], 'affirmation': [(aff['POS'], [14,23])] }),
("Come find us by Union Station today from 11:15am to 2pm 🤤 #arepas #patacones #empanadas #venezuelanfood #foodtruck… https://t.co/loxNI3jDYw", {'category': [(cat['NBR'], [16,29])], 'time': [(t['TOD'], [30,35]), (t['TIME'], [40,55])], 'affirmation': [(aff['POS'], [0,15])] }),
("Happy humpday! Come have lunch with us at L St and 19th St NW from 11:15am to 2pm. See you soon 😋 #arepas… https://t.co/uIc90Wi5R4", {'category': [(cat['ADD'], [42,61])], 'time': [(t['TIME'], [67,81])], 'affirmation': [(aff['POS'], [15,41])] }),
("Come have lunch with us at L’Enfant Plaza Station from 11:30am to 2pm. #arepas #patacones #venezuelanfood… https://t.co/rHlc8dBTq0", {'category': [(cat['NBR'], [27,49])], 'time': [(t['TIME'], [55,69])], 'affirmation': [(aff['POS'], [0,26])] }),
("RT @Mahou_DC: Mahou Session IPA on tap now @ArepaZone! #beer #cerveza https://t.co/bU42scrCT2", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @hylandwx: This Patacón from @ArepaZone is ginormous, but oh so tasty 😋 @UnionMarketDC https://t.co/fMvJcgHU4n", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @isalara: Recogiendo un pan de jamón! 😛 (at @ArepaZone in Washington, DC) https://t.co/AwgQw1JKo7", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @renerincon: @porlagoma @jesusalemarin @ArepaZone Si M&amp;M fue muy grato ver a ‘Eterna Juventud’, muy buenos recuerdos de Venevisión y Tel…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @porlagoma: Alegra tanto ver a los venezolanos que tienen éxito con sus emprendimientos en Estados Unidos, como mis amigos queridos de @…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @LizarazNava: @porlagoma @ArepaZone La mejor arepa que he disfrutado en mi vida. Ricas!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @CapHarvestDC: Make your taste buds dance this Friday by picking up one of @ArepaZone's famous arepas for lunch! Some of their many opti…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @cecasanovap: Juego del DC United: ¿Los cánticos? En español. ¿La comida? La gente de @ArepaZone tiene a medio estadio comiendo arep…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @PopeDupontCircl: If you are looking for lunch in Sunday-desolate downtown DC, @ArepaZone is a great option on 14th https://t.co/vhFucNu…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @freedomlovererh: Missed @ArepaZone so much when I was away! so glad to be back :) https://t.co/eanmDvOnUa", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @SmorgasburgDC: If you haven't grabbed a tostones trio from @arepazone, what are you waiting for? Referred to as a patacón, it's a mouth…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @AllThingsGo: The Fall Classic food lineup is here! Let us know what eats you’re most excited for in the replies 🍔 #ATGFallClassichttp…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @Amused_Jade: Chicha de arroz, patacon con Pollo, and cachapas con carne#food #foodpics #foodie #dcfoodie @arepazone https://t.co/QTeH…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @tolimolidc: Thank you for including us, @Eater_DC ! Love to see your friends @ArepaZone x Kuya Ja's Lechon Belly, and more on the list…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @RobertoNasser: @luciovilla @ArepaZone for awesome Venezuelan food!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @NaniaWTOP: Everything we do, we’ve made it a macro version of our family’s recipes … Just calling the matriarchs in both of our familie…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @byamichelle: Still regretting the day my Venezuelan friend introduced me to the @ArepaZone around the corner. So delicious and so impos…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Laissez les bon temps rouler 🎉 Get your king cake doughnuts, baby not included this #mardigras. Available in DC and… https://t.co/dzs6PerpQa", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("We’re at Farragut Square for lunch today DC! Catch us from 11:30-1 😎", {'category': [(cat['NBR'], [9,24])], 'time': [(t['TOD'], [35,40]), (t['TIME'], [59,66])], 'affirmation': [(aff['POS'], [0,8])] }),
("The perfect cheddar biscuit &amp; fried chicken-what more could you want in a breakfast? 📸: @lindakuehl #astrodoughnuts https://t.co/S4PQdpPRdG", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Good morning DC! Catch us at L’Enfant Plaza from 11:30-1pm today 😋", {'category': [(cat['NBR'], [29,43])], 'time': [(t['TIME'], [49,58]), (t['TOD'], [59,64])], 'affirmation': [(aff['POS'], [17,28])] }),
("Returning to work after a long weekend bites-luckily our chocolate covered strawberry doughnuts taste pretty great… https://t.co/JBGiZveUD3", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("We know it might not feel like summer outside, but one bite of our Key Lime doughnut and it's suddenly sunny &amp; 75 😎… https://t.co/kCerlKvLr9", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("DC: the truck is at Farragut today from 11:30 to 1 🤘🏻", {'category': [(cat['NBR'], [20,28])], 'time': [(t['TOD'], [29,34]), (t['TIME'], [40,50])], 'affirmation': [(aff['POS'], [4,19])] }),
("Hey, LA! Catch the Astro Truck in today from 11-2 in Playa Del Rey! https://t.co/fT83xI7E4D", {'category': [(cat['NBR'], [53,66])], 'time': [(t['TOD'], [34,39]), (t['TIME'], [45,49])], 'affirmation': [(aff['POS'], [9,39])] }),
("Have you ordered your #Valentines yet 💘? Surprise your loved ones with a mini box of these beauties via the link in… https://t.co/79VwnvEVWK", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("We've got our 👀 on the prize today//📸:@fooodmuncher #astrodoughnuts https://t.co/w74xL21y4M", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Union Station friends! Find our truck today from 11:30-1:00. See you soon!", {'category': [(cat['NBR'], [0,13])], 'time': [(t['TOD'], [38,43]), (t['TIME'], [49,59])], 'affirmation': [(aff['POS'], [23,43])] }),
("Nothing says 'I Love You' quite like a box of doughnuts 💘 Share a box with that special someone or at your Galentin… https://t.co/V3CNYQECZj", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("NOMA friends, we’ll see you on the truck today from 11:30 to 1:00. Happy Friday 🙌", {'category': [(cat['NBR'], [0,4])], 'time': [(t['TOD'], [41,46]), (t['TIME'], [52,65])], 'affirmation': [(aff['POS'], [14,46])] }),
("The perfect lunch doesn't exist....oh wait 😎 Pre-order yours at https://t.co/6yG5Eyqf7V 📸: @thejenchase https://t.co/8mgodtHUky", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Our love language is doughnuts 💘 🍩: Blood Orange Mimosa with orange-champagne glaze, chocolate drizzle &amp; gold spri… https://t.co/kHQZlu5gOX", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Say good morning to Key Lime Pie, Blood Orange Mimosa, Tiramisu &amp; Chocolate Covered Strawberry, available all Febru… https://t.co/g4Kw6qO2TY", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Celebrating #FryDay in NOMA this morning! Catch the truck from 11:30-1", {'category': [(cat['NBR'], [23,27])], 'time': [(t['TIME'], [63,70])], 'affirmation': [(aff['POS'], [42,62])] }),
("We’ll be at L’Enfant Plaza today from 11:30-1:00. See you soon!", {'category': [(cat['NBR'], [12,26])], 'time': [(t['TOD'], [27,32]), (t['TIME'], [38,48])], 'affirmation': [(aff['POS'], [0,11])] }),
("RT @DCSLIDERSTRUCK: Say yes to jobs &amp; city revenue &amp; pass complete food truck ordinance @TimLovain #AlexandriaHeartsFoodTrucks 🍔🍔", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("hi everyone looks like we are taking off for a week vacation wilbe back soon", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("http://t.co/ffFrNASthI", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @TopDogTruck: @Partytrucks thanks for lunch.  I like the new falafel recipe.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @TopDogTruck: @Partytrucks thanks for lunch yesterday.  The chicken was delicious.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @richcadieux: @RestonPatch View from my front door on Barrel Cooper Court http://t.co/u3UJjixo", {'category': [(cat['ADD'], [57,76])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @CarisSevern: @RestonPatch You can tell it's not Reston, though - the phone-pole thingie... http://t.co/ZQ6fp2gS", {'category': [(cat['NBR'], [52,58])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @KC_Kreative: Thanks @PartyTrucks (ATIP) and @Scoops2u for a super tasty lunch today. Nothing like a gyro and 'chipwich' to fill you up!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Serving at @ResidenceInn Largo - 1330 Caraway Court  Largo From 5:30PM-8:30PM EDT http://t.co/lA7xharyp6", {'category': [(cat['ADD'], [25,51])], 'time': [(t['TIME'], [64,77])], 'affirmation': [(aff['POS'], [0,10])] }),
("At navy yard ready to open", {'category': [(cat['NBR'], [3,12])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [13,26])] }),
("Ready to serve at friendship heights", {'category': [(cat['NBR'], [18,36])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [0,17])] }),
("Ready to serve our Delicious angus bulgogi at friendship heights", {'category': [(cat['NBR'], [46,64])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [0,14])] }),
("We are here at navy yard with angus aeye round bulgogi and fusion tacos", {'category': [(cat['NBR'], [15,24])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [0,14])] }),
("We here at Virginia ave folks", {'category': [(cat['ADD'], [11,23])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [0,10])] }),
("Friendship heights", {'category': [(cat['NBR'], [0,18])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("We are at lenfant plaza serving our delicious bulgogi, fusion tacos and spicy pork subs", {'category': [(cat['NBR'], [10,23])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [0,9])] }),
("Navy Yard on this rainy Friday!", {'category': [(cat['NBR'], [0,9])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [10,30])] }),
("Good morning! We are at the State Dept on Virginia ave &amp; 20th! Look for the red truck :)", {'category': [(cat['ADD'], [28,65])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [14,27])] }),
("No parking at Friendship Heights.. We'll be back tomorrow!", {'category': [(cat['NBR'], [14,32])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [35,57]), (aff['NEG'], [0,13])] }),
("Sorry everyone! Change of plans.. Heading to Friendship Heights. We'll be back to State Dept next Wed.", {'category': [(cat['NBR'], [45,63])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [34,44]), (aff['POS'], [65,81])] }),
("State Department (Virginia Ave) today!", {'category': [(cat['ADD'], [0,31])], 'time': [(t['TOD'], [32,37])], 'affirmation': [(aff['POS'], [32,40])] }),
("We are at 20th and L St today next to Wells Fargo!", {'category': [(cat['ADD'], [10,23])], 'time': [(t['TOD'], [24,29])], 'affirmation': [(aff['POS'], [0,9])] }),
("Navy Yard today! Windows up in 15mins!", {'category': [(cat['NBR'], [0,9])], 'time': [(t['TOD'], [10,15])], 'affirmation': [(aff['POS'], [17,30])] }),
("Happy Friday! Union Station today!", {'category': [(cat['NBR'], [14,27])], 'time': [(t['TOD'], [28,33])], 'affirmation': [(aff['NULL'], [])] }),
("Friendship Heights today! @FeedFHeights @MazzaGallerieDC", {'category': [(cat['NBR'], [0,18])], 'time': [(t['TOD'], [19,24])], 'affirmation': [(aff['NULL'], [])] }),
("#arlington we're rocking long bridge park today. Come check us out for some fish tacos on a hot day.", {'category': [(cat['NBR'], [25,41]), (cat['NBR'], [1,10])], 'time': [(t['TOD'], [42,47])], 'affirmation': [(aff['NULL'], [])] }),
("Thx @TommyWells for standing up for food trucks!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Thanks @VincentOrangeDC for putting forward better food truck regs!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Getting ready for the rest of the week. See you all soon.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("We are not serving food, so sorry", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [0,17])] }),

# Only Affirmation, without location tagging from here on

("Thank you @TommyWells for your strong support for our local food trucks &amp; for your amendment!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("#CrystalCity we'll be serving up warm Cuban sandwiches and cold drinks. Come check us out.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("#ballston, balstatonions get ready for the cubanators!!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Gotta take a day off, Tour de Fat was too much fun. See you tomorrow.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("#tour de fat today. Come down to Yards park and try your favorite Cuban speciality paired with New Belgium beer.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Council Committee votes to reject proposed regs! THANK YOU @VincentOrangeDC @JimGrahamWard1 @GrossoAtLarge @CMYMA @marycheh!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("#rossyln, uh oh rosslynators, watch out here comes the Cubanator. 'Get to the choppa'", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("What's better than fresh Cuban food? Cuban food with a new Belgium beer! See us this weekend at the tour de fat.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("#crystal city, don't forget about the tres leche cake!!!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Everyone come see us this weekend at the Tour de Fat to try our specialities paired with different beers. Suggestions?", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("#arlington courthouse, no signs of rain come try a delicious Cuban!!!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("#arlington court house, we will have Cubans and burritos ready to go from 11-2 so if its raining don't worry it will only be just a second", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("#Rosslyn, don't worry be happy a lo Cubano is here.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("our new schedule, mon- rosslyn,tues-Arlington court house, wed-crystal city,Thursday-ballston, fri-rosslyn", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("'@StationCDRKelly: Day 121. The #Nile at night is like a jewel. Good night from @Space_Station! #YearInSpace http://t.co/L17WDcvk14'MY PEEPS", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @StationCDRKelly: Day 121. The #Nile at night is like a jewel. Good night from @Space_Station! #YearInSpace http://t.co/T6TTkVyiRw", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("'@MrTerrificPants: Omg. Why do we put cheese on EVERYTHING?!?' Because it makes it Pretty...", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @CapitolRvrFront: Packing ur #FridayNightConcert picnic? Many #CapitolRiverfront options + @Agua301WDC @BabasBigBite @bigcheesetruck! ht…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Please help this child if you can. Check it out  http://t.co/kiFxsXkMNh", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @timelesstrendsb: So excited to have Baba's Big Bite joining us this Saturday for our grand opening in Aldie! Yum yum yum! http://t.co/v…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @BallstonBID: #CourageWall coming to #Ballston tomorrow! Check it out and make an affirmation at Welburn Square starting at 4pm http://t…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Whats up Rosslyn Baba's Is curbside flipping some Deliciousness.🍔 Come by &amp; Grab a Bite.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Whats up 20th &amp; L st Babas is Curbside serving up some Deliciousness. Its been too long...", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("'@burgerdays: Burger Days Rated Rookie.  https://t.co/W8yDy3QWGX' LIKE AH BOSS", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @burgerdays: Burger Days Rated Rookie.  https://t.co/c96EyuWViY", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("We're parked in front of @ABC7News", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Whats up Rosslyn Baba's Is curbside serving up some Deliciousness. Its been too long", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("RT @MensHumor: #math http://t.co/jw5l0DAI6q", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Hey Rosslyn Baba's Is not curbside flipping today Deliciousness. No burgers sorry.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Bad News! We are not serving today.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Wishing you, your family and friends very Happy Holidays and Happy and wonderful New Year!!!#happyholidays… https://t.co/EBAtQg8CAB", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @7LocksBrewing: @balkaniktaste is here and we have The Walkaways playing from 7:30-10pm with their friends Wes Tucker and the Skillets a…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Finds us today at @7LocksBrewing. Window open 4:30pm-7:30pm. Join us for last time this year and grab delicious… https://t.co/D5ZqYadldn", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("RT @7LocksBrewing: #FoodTrucks: We have @TrippyTacos240 tomorrow Dec. 19 and @balkaniktaste Saturday, Dec. 21! https://t.co/mflMJyYk50", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Find us today at 15400 Calhoun Dr, Rockville. Window open 11am-2pm.#balkanfood #balkanfoodtruck #kyufte… https://t.co/vRMFXlvJ1T", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("RT @curbsidekitchn: Catch @balkaniktaste tomorrow for Lunch at 15400 Calhoun Dr, RockvilleDeliciousness brought to you by @curbsidekitchn…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Find us today at Windridge winery, Darnestown, MD Window open 1pm-6pm.#balkantruck #balkanfood #kyufte… https://t.co/aFw2bzfY8J", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Find us today at @7LocksBrewing for delicious Balkan Grill and good local beer. Window open 4:30pm-8pm.… https://t.co/a1SasnEyjg", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Wish you very happy and blessed Thanksgiving!#thanksgiving #holiday #family #familytime #turkey #balkanfoodtruck… https://t.co/1I9LIOjAc6", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Find us today at @TrueRespite in Rockville. Window open 4pm-8pm.#balkanfood #balkanfoodtruck #pljeskavica #kyufte… https://t.co/Pdf9q2r8Uq", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Tonight we will be serving dinner at @mallorysquareapts in Rockville. Window open 5pm-8pm. See you there!… https://t.co/FuzkPeefpw", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Serving lunch today at 6701 Democracy blvd, Bethesda. Window open 11am-2pm.#bethesda #balkanfoodtruck #balkanfood… https://t.co/sFXME5Ggj5", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("RT @curbsidekitchn: Catch @balkaniktaste today for Lunch at Democracy One Plaza, 6701 Democracy Blvd, North BethesdaDeliciousness brought…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("RT @curbsidekitchn: Catch @balkaniktaste tomorrow for Lunch at Democracy One Plaza, 6701 Democracy Blvd, North BethesdaDeliciousness brou…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Today we will be at @7LocksBrewing. Window open 4:30pm-8pm. Stop by for delicious #balkangrill and good beer.… https://t.co/pvGS6ojAPX", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("RT @7LocksBrewing: #FoodTrucks this week: Thursday- @TrippyTacos240 Friday- @smoke_bbq Saturday- @balkaniktaste https://t.co/RKP3OSZ0Ml", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Today we are at @7LocksBrewing. Window open 4:30pm-8pm. 7 Locks created a soecial paring menu. Make sure to stop by… https://t.co/DQ9vtLZTzR", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("RT @7LocksBrewing: It's @balkaniktaste 5th Anniversary today! Come celebrate with them at 7 Locks today! Receive a ticket for $1 off pints…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("We are at @elderpinebeer tonight. Stop by and try theyr new beers and join us for Halloween party.#halloween… https://t.co/XHeLEmH93K", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Today’s menu for Franklin Square: https://t.co/jHufDwaAzj", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("We're closed today, catch us tomorrow at China Town!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Closed for today. We'll be at 7 Locks tomorrow! Make sure to stop by… https://t.co/DQ9vtLZTzR", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Out of tamales, we'll be back tomorow at George Forman Square", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Rainy Thursday, no partying for us today.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("RT @TheLoopConnect: A brand personality influences every aspect of a brand including its logo, brand colors, website design, social media c…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Franklin Square we are parked and ready to serve!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Sorry, metro, going to Franklin Square now.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Just a couple of the sides available with meatballs on the truck today at metro center. Roasted Brussels Sprouts wi… https://t.co/SL6QiKjtaK", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Today’s menu for Metro Center: https://t.co/5b7cLyYe9S", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Metro center today!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Tomorrow: Metro Center!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("State Department today!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Tomorrow: State Department!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Today’s menu for Union Station: https://t.co/GD2mFPWzLZ", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Union Station today!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Awww, thanks! https://t.co/fvtorwNLXr", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Tomorrow, Monday, President’s Day: Franklin Square!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("RT @allinwithchris: Watch the full opening monologue here: https://t.co/LZ38MMvRe7 #inners", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @jdawsey1: Trump mocks prayers of others, but his own beliefs remain opaque. On a president beloved by evangelicals who has accomplished…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Franklin Square, we gonna be back on Monday because President’s Day and because we love you.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Super nice out, Franklin! And online so food is coming out verrrrryyy fast...", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Banh Mi Annie will be in Takoma Park today!!!! 201 Ethan Allen Ave 5-8. @TakomaParkMD @MainStTakoma", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Another great night in Takoma Park. Thanks everyone for the great support!! Have a great weekend! @MainStTakoma @TakomaParkMD", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Join Banh Mi Annie tonight at 201 Ethan Allen Ave, Takoma park. 5-8We now serve Papaya Salad with 5 Spice Beef!!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("5635 Fishers Lane, Rockville MD11-2 Text your order to 5713543980!!!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Banh Mi Annie is heading to Fishers Lane today!!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("It was a really good night for us. Sold out in less than 2 hrs. Thanks for the great support. Have a great weekend!! @MainStTakoma", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("We're coming to Takoma Park tonight with @hardysbbqdivine. It's a beautiful day!! 201 Ethan Allen Ave, Takoma Park5-8", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("We will be at 9715 keywest ave, Rockville 11- :)", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Good morning!! Banh Mi Annie is heading to Key West Ave today!!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Banh Mi Annie is heading to Fishers Lane today 11:30- Plenty of soup and yummy sandwiches to warm you up. Text your order to 5713543980", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Banh mi Annie is heading to Key West Ave, Rockville today!! 11-2", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Join us today for TET festival at Northwood HS on University Blvd 11-4. There will be no Banh mi but lots of other goodies!!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Traffic is bad. ETA 5:30", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Join us tonight in Takoma Park with @CurleysQ @ 201 Ethan Allen Ave!!!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Text your order to 5713543980!!!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Good morning! Banh Mi Annie is heading to 9705 Key West Ave today!! 11-2", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Patriots Plaza! Headed your way today!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("NoMa! Fresh From Scratch lasagna today. Tell a friend; see you at 11:30!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Union Station!  Come on out - grab some tasty, From-Scratch Lasagna - soooo many kinds to choose from!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Union Station!  Today is a great day for from-scratch deliciousness!  See you ~ 11:30 - tell a friend!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Unexpectedly Had to move folks  :(       Cap South We are Here!! :)", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Patriots Plaza! Kick off the short week right -with a delicious BT lunch!  See you at 11:30 - tell a bud!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Cap South! Break for lunch should be betwern the raindrops today. Come on out and grab delicious lunch!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Patriots Plaza!  Come on down and enjoy some Lasagna!!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("NoMa! What makes a beautiful day even more beautiful?  An amazing lunch! See you ~11:15", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("20th and L! It's Basil Thyme today. Grab a buddy and come on down!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Union Station! Lasagna goodness - super fast!  See you soon; bring a friend!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Union Station!  See you for Friday Lunch!! Super Fast, super tasty!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Cap South! Tasty Lunch is on the way!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Noma!  It's Almost Basil Thyme", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Union Station!  So sorry but no, from-Scratch Lasagna, we'll be back!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Union Station! Tomorrow is a good day for from-scratch deliciousness!  See you mark your calendar!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Unexpectedly Had to move folks  :( wont be coming back", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Will kick off the short week right at Patriots Plaza! See you on Friday!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Break for lunch will not be with us.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("I know you're hungry Farragut Square, but we can't feed you.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("NoMa! What makes a rainy day sad? Us postponing to tomorrow", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Union Station- did you get your Basil Thyme yet? It's not too late - go for it!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Union Station!  End the week deliciously with Basil Thyme!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Metro Center! We're up by the Marriott today. See you around 11:30+ for the most delicious Thursday lunch!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Patriots Plaza - did you get your Basil Thyme yet today?!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Patriots Plaza! Let's make great lunch happen Today!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Union Station!  Come out for some super fast, super tasty lunch!  See you shortly - grab a friend!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("RT @perubrothers: After 7 years promoting Peruvian food and culture through our catering and food trucks, we opened our first brick-and-mor…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("It’s time for a BBQ lunch at L’Enfant Plz! Order online + skip the line + save $3 promo code BBQBus https://t.co/mfGlKZnE70", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Lunch today at L’Enfant Plaza!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Lunch today at Thomas Jefferson + K St NW! Order ahead online + save 3 Bucks w promo code BBQBus https://t.co/mfGlKZnE70", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Here we come Georgetown!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Join us for RIBS, Angus brisket, mac+cheese + all your other smoky faves today at L'Enfant Plaza. Order ahead… https://t.co/YGDrmupBGS", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Lunch today at L'Enfant Plaza!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Congrats @rocotohotsauce on ribbon cutting lacosechadc +thx for a great party! @ La Cosecha https://t.co/v3CQfh7LrW", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Lunch today in Georgetown! Preorde + we’ll comp you $3! https://t.co/mfGlKZnE70 promo code BBQBus", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("It's Monday Funday at BBQ Bus! Lunch today at Union Station: Order online and save $3 w promo code BBQBus at https://t.co/mfGlKZnE70", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Lunch today at Union Station!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("RT @SmallBizDC: Director @WhitfieldKristi was honored to host @MayorBowser's Every Opportunity to Rise Podcast for the launch of Season 2!…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Preorder lunch today + we’ll comp $3 off your meal! https://t.co/mfGlKZnE70 promo code BBQBus", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Lunchtime L’Enfant Plaza! Come on out for quarter + half slabs of RIBS, slow smoked pork and brisket + mac+cheese! Window opens at 11", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Lunch today at L’Enfant Plaza!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Plus pre-order + skip the line + save $3 w promo code BBQBus https://t.co/mfGlKZnE70", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("It's a BBQ lunch at Georgetown today! Serving up oh so good Angus brisket, smoky pulled pork, mac+cheese + more! Window opens at 11!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("RT @AstroDoughnuts: Say good morning to Key Lime Pie, Blood Orange Mimosa, Tiramisu &amp; Chocolate Covered Strawberry, available all February…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Plus pre-order + skip the line + save $3 w promo code BBQBus https://t.co/mfGlKZnE70", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Enjoy the warm Feb sunshine w us today at Union Station! Serving RIBS, pulled pork, Angus brisket + mac+cheese + al… https://t.co/4G6hKBUYbt", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("https://t.co/r61LxlEvzg https://t.co/WHzE602pLc", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("No food today!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("No food today", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("No food at all", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("You will find no food here today Georgetown.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("We will not be serving.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("So sorry but there will not be any food today", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Can't make it today, will be back tomorrow!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Hungry? Well sorry we aren't going to serve today", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("No parking in Georgetown, will be coming back tomorrow", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Our kitchen is on fire, no food today", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Memorial Day commemorates the Men and Women who died while in the military service of their country, particularly t… https://t.co/mfbAfEiTRr", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("One of the bad things about not being out on the Beach Buggy are my thoughts of new ideas of what I'm thinking of b… https://t.co/fhqiBy1Bcz", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Picnic in the Park is a go for Today.Beach Fries won't be there but we have Taco Tuesday filling in for us with t… https://t.co/W9yxhzndwJ", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Good Day everyone.Just an update on my current situtation. Last nights issue at the ER, all tests came back negat… https://t.co/JWTFFSZ91k", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Back in the ER right now. Concerned with sharp pains in my lower abdomen. Not taking any chances since my surgery o… https://t.co/pcdqcQLP9g", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("I'd like to thank everyone for all the continued support through my whole ordeal over the last week.Unfortunately… https://t.co/LTR0R7BaO3", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Thanks to everyone's well wishes this week following my injury Tuesday night. I appreciate all the care and concern… https://t.co/9xuhqrohty", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Beach Fries Nation! Its official, the voting has commenced and continues until March 18th.We appreciate your ev… https://t.co/g2W9UEPVUY", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("There's a ton of Very Talented 'Food Trucks' located in or around the surrounding areas of Fredericksburg, Virginia… https://t.co/J7L13u3afH", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Rain, Rain go away, Come back some other day!Well it looks like Friday, March 1st might not be the greatest day w… https://t.co/JJQln8wVnx", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("It's that time of the year folks to nominate and vote for your favorite businesses throughout the Burg and surround… https://t.co/Sfl6rpbGcb", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("The Beach Buggy will be heading out to a North Stafford Brewery for our first time.Beach Fries will be onsite at… https://t.co/Ueyhtz1yaN", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Just wanted to give a huge THANK YOU to all the Faculty, Student body and family/friends at Battlefield Middle scho… https://t.co/dV21PHIalg", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Have Yourself a Very Merry Christmas!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("I posted a new video to Facebook https://t.co/amwb5DyTVK", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("I posted a new video to Facebook https://t.co/oPGttD7mWX", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Hope to see you tonight next to Spencer Devon Brewing.Our Feature and only sandwich will be our new item. Pulled… https://t.co/GX84Mwy2jV", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Beach Fries will be at Old Bust Head Brewing Company tomorrow, Thursday the 29th. Serving from 3-8pm.Happy to be Back at OBH!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Happy Thanksgiving from our home to yours!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("At state department", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At metro center", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At L'enfant plaza", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At metro center", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At l'enfant plaza", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At metro center", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At Metro Center", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At L'enfant plaza", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At State department", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At L'enfant plaza", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At Navy Yard", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At Waterfront metro", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At State department", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At Farragut square", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At State Department", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At L'enfant plaza", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At Farragut square", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At Farragut square", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At Farragut square", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("At State Department", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Good morning today we are going to be a Farragut square come on out today I know it's a little… https://t.co/doxUy6FS8t", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Good morning come out to join us today Virginia Avenue (State Department) 200 Block Virginia… https://t.co/HTnQme7IGV", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("GOOD MORNING LADIES AND GENTLEMEN ARE YOU IN THE MOOD FOR SOME GOOD FOOD WELL WE CAN HELP YOU… https://t.co/nlASlkaWk7", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Good morning today bellavita is going to be at noma plaza @ NoMa / H Street NE https://t.co/KgsrfXk01A", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("foodtruckfiesta Bella Vita Italian Wheels today at Virginia Avenue (State Department) 200 Block… https://t.co/Q9fxViTx9s", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Ladies and gentlemen I know it's been awhile but here we are today we are at a new location we… https://t.co/UwrrjaFOeF", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Good morning I know y'all are hungry well here we come l'enfant plaza come on out today @… https://t.co/DvEwG4bfmh", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Hello pasta lovers Bella vita Italian wheels will be at 12th Sw DC come out today in front of… https://t.co/i1PnN3BDml", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Sorry I'm late this morning but today we on 17th st NW DC at the Farragut park come on out and… https://t.co/L6VrEiGZuV", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("I'm hungry how bout you today we are at the lovely L'ENFANT plaza come enjoy todayfoodtruckfiesta… https://t.co/do3aybQtLx", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Hello Italian and wine lovers today we will be wineryatbullrun come on out and try to delicious… https://t.co/XIdLFPyS34", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Hello Italian and wine lovers today we will be wineryatbullrun come on out and try to delicious… https://t.co/i4JTZaQ376", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Hello today we are at Franklin square come on out today to enjoy some lovely Italian foodFranklin… https://t.co/cBNYLZobNj", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Gmorning guys today Best Mexican Burritos at Dupont circle  see youu.!!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("G morning guy's  Best mexican Burritos in noma today see you..!!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Best mexican Burritos in noma, coming soon see you tomorrow!!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Tomorrow's the day! Join us &amp; our Food Truck friends @Truckeroo 4 Tasty Eats, Live Music and Cold Beer! @Fairgrounds_DC Half &amp; M SE", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Tomorrow's the day! Join us @Truckeroo 4 Tasty Eats, Live Music and Cold Beer! @Fairgrounds_DC Half &amp; M SE@Coles_Palette", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Bonjour DC! We're off the streets today. Find us tomorrow at Chevy Chase farmers market on Taylor &amp;Brookville rd 8a… https://t.co/O6VcN3SudU", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Bonjour DC! We're off the streets today. Happy holiday everyone! Find us tomorrow at Union Station on Mass ave &amp; No… https://t.co/iJHje2CHsV", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Bonjour DC! We're off the streets today. We'll be back tomorrow at Chevy Chase farmers market on Taylor &amp;Brookville… https://t.co/slEJ0lc1YW", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Bonjour DC! We're off the streets today. It's time to go renew our licenses. We'll be back tomorrow at Chevy Chase… https://t.co/Mm5XksTy5L", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Friendly Reminder! Don't eat at home tomorrow. Visit Curley's Q under tent 10am-5pm. Takoma Park Street Fest… https://t.co/5DePp5WWb3", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("RT @roamingrooster1: Hello Roaming Rooster Family! Tomorrow starting at 4pm, one of our trucks will be posted at the newly opened Smitty's…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("RT @truckeroo: Tomorrow is the last Truckeroo of the season! Come out to celebrate the start of an amazing weekend. See you there!Trucker…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("We have missed ALL our fans in #Tysons speared the news we are there for lunch tomorrow #vegan #Egyptian #yummy… https://t.co/uviH5VhAL1", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Good morning! Yellow Tin heads towards to US ICE today. See you all during lunch hour.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Good morning Navy Yardian! Yellow Tin landed in front of Five Guys. See you all during lunch hour.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Good morning! Yellow Tin heads towards to Navy Yard today. See you all during lunch hour.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Good morning! Yellow Tin heads towards to Metro Center today. See you all during lunch hour.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Good morning! Yellow Tin heads towards to US ICE today. See you all during lunch hour.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Good morning! Yellow Tin landed at Farragut Square to serve lunch today. See you all during lunch hour.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Good morning! Yellow Tin heads towards to Reston Business Center Dr. See you all during lunch hour.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Good morning! Yellow Tin will not head towards to US ICE. Wont see you during lunch hour.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Good morning Navy Yardian! Yellow Tin is not landing in front of Five Guys. Sorry will not see you today.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Good morning! Yellow Tin is not heading anywhere. Bye!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Good morning! Yellow Tin cancelling Metro Center today. Be back tomorrow!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Good morning! Yellow Tin will not be at US ICE today. No food sorry", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Good morning! Yellow Tin will be back at Farragut Square tomorrow. For lunch.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Good morning! Yellow Tin is not going to be at Reston Business Center Dr. We are going home", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Hey @DrMolecules, Thank you for the follow!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Hey @ETTORI_MAGA, Thank you for the follow!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Hey @jordan_leikin, Thank you for the follow!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Hey @anika_krishnan, Thank you for the follow!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Hey @goodfoodmmm, Thank you for the follow!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Hey @asgharboa, Thank you for the follow!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Hey @JAOrquina, Thank you for the follow!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Hey @BostonFoodPops, Thank you for the follow!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Hey @Thuring6, Thank you for the follow!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Hey @orepia09, Thank you for the follow!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Hey @NYRZombieDJP, Thank you for the follow!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Hey @JamesWiglees, Thank you for the follow!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Hey @SahgalN, Thank you for the follow!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("We will be at 17th &amp; K today", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("RT @TheMoCoShow: You ever grab breakfast at BLT Grill in Gaithersburg near Lakeforest? All of this was $19 (last two pics are of the same…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Happy Jayden Day. Enjoy 1/2 off ices, gelatis, &amp; fall gelatis at the shop today. Open until 10:30pm https://t.co/w1PeW1yDT9", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("RT @TheMoCoShow: Carmen’s Italian Ice to Open Olney Location @CarmensCarts Details here:https://t.co/11huoQ5jsQ", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("It starts today! Never too cold for Carmen’s. https://t.co/sileAcqsd4", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Happy Jayden Day! Enjoy 1/2 off ices, gelatis, &amp; fall gelatis today. Open until 930pm https://t.co/WBVoJnDNYv", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("We love being a small business! Shop local today in MOCO, &amp; don’t forget to stop by the shop for our best deal of t… https://t.co/x6R4cAatcA", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @FinestEducator: Shout out to @CarmensCarts for being a business that always supports its community.  Friendly staff and their ice alway…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("One of Jayden’s classmates, please retweet https://t.co/PJbE6dD4Lh", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @1067theFan: #Wizards coach, Scott Brooks tells the media before their game with the #Rockets,  'We won't call many time outs tonight.…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Let’s go Max! Don’t forget the dessert. Plenty available in our Grab N Go Freezer. @dailynatitude https://t.co/M03jjcFLKH", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @MollyCocktail: When my burger was ready, the clerk called out “867?”I yelled back 5309. No one laughed.I am old.", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @MannaFoodCenter: Our Board member, Matt of ⁦@Cigna⁩, treated staff &amp; volunteers to ⁦@CarmensCarts⁩ as a thank you treat. We are 7 days…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Happy Jayden Day! 1/2 off Ices &amp; gelatis @ the shop today. Open til 9pm https://t.co/hwhukiXzWY", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("RT @InterfaithWorks: What a beautiful day 😍 for the Park Potomac Ice Cream Social for Charity! We are here collecting 🎒 and school supplies…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Krazy Steve's on #Google https://t.co/5VoRH6YNSS", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Truck #3 Farragut. Beautiful day means incredible BBQ Mac Greens and we’re keeping that Nat’s Spirit alive w our Wo… https://t.co/FN58WeLcnZ", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("RT @carnbbq: Truck #3 Georgetown. Keeping that Nat’s spirit alive w the amazing World Series Winner Specials all week", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Truck #3 Union. Best BBQ, Mac &amp; so much more!", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Missing girl from Rockville MD. To all:  Please disseminate and help get her home https://t.co/P9XHQ7Xl60", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Truck #3 Farragut. Continuing Celebrating the Nat’s w our World Series Specials in BBQ &amp; Mac and check out our free… https://t.co/W1ckIaOtkZ", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("RT @carnbbq: Amazing Free Rib &amp; Pizza Dinner Open House at https://t.co/oLeClSXxS4 Tonight through Thursday Lines form 4-8pm. https://t.co/…", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("Amazing Free Rib &amp; Pizza Dinner Open House at https://t.co/oLeClSXxS4 Tonight through Thursday Lines form 4-8pm. https://t.co/JuYjYJVYOq", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("And look for Krazy Steve’s Free Rib &amp; Chicken Dinner 4-8pm this Tuesday Wednesday &amp; Thursday at Krazy Steve’s 1909… https://t.co/A72qHLkBC1", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NEG'], [])] }),
("Truck #3 Georgetown. Keeping that Nat’s spirit alive w the amazing World Series Winner Specials all week", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
("Did it ever occur to Trent Williams (or the press for that matter) that in addition to his team’s physician, he mig… https://t.co/SldDDatOkG", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }),
("RT @carnbbq: Truck #3 L’Enfant", {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['POS'], [])] }),
]

# {'category': [(cat['NULL'], [])], 'time': [(t['NULL'], [])], 'affirmation': [(aff['NULL'], [])] }

def validate_train_data(train_data, show=False):
    len_data = len(train_data)
    print(len_data)

    i = 1

    for tweet in train_data:
        tweet_data = tweet[1]
        
        print(f'Tweet {i}')
        print(tweet[0])
        i += 1

        if 'category' not in tweet_data or 'time' not in tweet_data or 'affirmation' not in tweet_data:
            print(f'ERROR: Missing key {tweet_data}')
            continue
        
        if show == True:
            if tweet_data['category'][0][0] != cat['NULL']:
                j = 1
                for category in tweet_data['category']:
                    print(f'{category[0]}: {tweet[0][category[1][0]:category[1][1]]} ', end = '')
                    j += 1
                print('')
            
            if tweet_data['time'][0][0] != t['NULL']:
                j = 1
                for time in tweet_data['time']:
                    print(f'{time[0]}: {tweet[0][time[1][0]:time[1][1]]} ', end = '')
                    j += 1
                print('')

            if tweet_data['affirmation'][0][0] != t['NULL']:
                j = 1
                for affirmation in tweet_data['affirmation']:
                    print()
                    if len(tweet_data['affirmation'][0][1]):   
                        print(f'{affirmation[0]}: {tweet[0][affirmation[1][0]:affirmation[1][1]]} ', end = '')
                    else:
                        print(f'{affirmation[0]}', end = '')
                    j += 1
                print('')
        
        print('_____')
        print('')

validate_train_data(train_data, True)