const {
  REACT_APP_VENDOR_API,
  REACT_APP_MAPBOX_API_KEY
  } = process.env;

const VENDOR_API = REACT_APP_VENDOR_API;
const MAPBOX_API_KEY= REACT_APP_MAPBOX_API_KEY;

export {
    VENDOR_API,
    MAPBOX_API_KEY
}