import spacy
import random
nlp = spacy.load("en_core_web_lg")
ner = nlp.create_pipe("ner")
nlp.add_pipe(ner)
ner.add_label("TRUCK_LOCATION")
nlp.begin_training()
TRAINING_DATA = [
    ("'This is my f**king country': Racist white woman arrested for attacking passengers on New York bus https://t.co/Rfm0jauh72", {'entities': []}),
    ("RT @mussie671: Freestyle #3, Fiasco type shiiii https://t.co/0GTJscWORW", {'entities': []}),
    ("What you think Cole? @JColeNC @JColeDirect https://t.co/oE4Ipvq6hL", {'entities': []}),
    ("⚡️Redskins dominate the Raiders on Sunday Night Football https://t.co/4VuHWOs1gX", {'entities': []}),
    ("RT @NWSSanJuan: 215PM FLASH FLOOD EMERGENCY for A Dam Failure in Isabela Municipality y Quebradillas Municipality in Puerto Rico... #prwx h…", {'entities': []}),
    ("Posted @chinatown on the corner of 7th &amp; D st. NW, PERFECT WEATHER TO SLIDE UP!!", {'entities': [(25, 53, 'TRUCK_LOCATION')]}),
    ("Good Morning DMV, we are @ChinaTown on the corner of 7th &amp; G st NW. Hand crafted burgers, endless toppings, Hand cut fries,  PULL UP !!!", {'entities': [(43, 70, 'TRUCK_LOCATION')]}),
    ("Good Morning DMV, we are @ChinaTown on the corner of 7th &amp; G st. NW serving our delicious hand crafted burgers and Home made fries. PULL UP!", {'entities': [(43, 71, 'TRUCK_LOCATION')]}),
    ("Good morning angry burger lovers, we are back in China town, 7th &amp; G st. NW serving our delicious hand crafted burgers and home made fries!!", {'entities': [(61, 79, 'TRUCK_LOCATION')]}),
    ("Good Morning Angry burger lovers, we are serving @Chinatown on the corner of 7th and G st NW. See you there!", {'entities': [(67, 92, 'TRUCK_LOCATION')]}),
    ("Good morning DMV we are @ChinaTown today, on the corner of 7th and F st NW. COME EAT ‘EM UP!!!", {'entities': [(49, 74, 'TRUCK_LOCATION')]}),
    ("Good morning angry burger lovers, we are serving on the corner of 25th &amp; M today, see you there!", {'entities': [(56, 78, 'TRUCK_LOCATION')]}),
    ("Good morning DMV, we are serving lunch China town on the corner of 7th &amp; D st NW. Come get you some!!", {'entities': [(57, 84, 'TRUCK_LOCATION')]}),
    ("Good morning angry burger lovers, we are @L’enfant plaza serving our delicious burgers and hand cut fries! See you there!", {'entities': [(41, 56, 'TRUCK_LOCATION')]}),
    ("Good morning DMV, we will be on the cornor of 19th &amp; L st. NW serving our delicious hand crafted burgers and hand cut fries. SEE YOU THERE!", {'entities': [(36, 65, 'TRUCK_LOCATION')]}),
    ("Good morning DMV, We are on the corner of 25th &amp; M st NW kicking out our delicious burgers, BMF’s and hand cut fries! Come get you some!!", {'entities': [(32, 60, 'TRUCK_LOCATION')]}),
    ("Good morning DMV, We will be serving @ 25th &amp; M today. See ya there!", {'entities': [(39, 51, 'TRUCK_LOCATION')]}),
    ("Good morning DMV, it’s a beautiful day, we’ll be @Chinatown on the corner of 7th &amp; G st. Serving our delicious burgers and hand cut fries!!", {'entities': [(67, 92, 'TRUCK_LOCATION')]}),
    ("Come enjoy lunch with us at Virginia Ave and 20th st NW from 11am to 2pm 😋 see you soon! #arepas #patacones… https://t.co/F3BQPKzWNf", {'entities': [(28, 55, 'TRUCK_LOCATION')]}),
    ("Happy humpday!! Find us at Farragut square from 11:30am to 2pm! 🤗 see you soon! #arepas #patacones #venezuelanfood… https://t.co/IENRYU3X0I", {'entities': [(27, 42, 'TRUCK_LOCATION')]}),
    ("Happy Friday!!! Come join us for lunch today at 20 Massachusetts Ave by Union Station from 11:30am to 2pm. See you… https://t.co/mb0RzawFgm", {'entities': [(48, 68, 'TRUCK_LOCATION')]}),
    ("Happy Friday!! Cone have lunch with us by 20 Massachusetts Ave. close by Union Station. Window open from 11am to 1:… https://t.co/rPOxYH2h32", {'entities': [(42, 63, 'TRUCK_LOCATION')]}),
    ("Happy humpday! Have lunch with us today at Farragut Square from 11am to 1:30pm. See you at lunchtime 😋 #arepas… https://t.co/1aGfOUvRJN", {'entities': [(43, 58, 'TRUCK_LOCATION')]}),
    ("Happy Friday! 🤗 come have lunch with us! today we are by 20 Massachusetts Ave. one block from Union Station. Will b… https://t.co/i9WpS2a3qp", {'entities': [(58, 79, 'TRUCK_LOCATION')]}),
    ("Happy humpday!! Have lunch with us today at Farragut Sq on 17th St NW from 11am to 2pm 🤤 see you at lunchtime!… https://t.co/uD8N5dv0c3", {'entities': [(44, 69, 'TRUCK_LOCATION')]}),
    ("Come have lunch with us today at L St and 18th St NW from 11am to 2pm. 😋 #arepas #patacones #venezuelanfood… https://t.co/iAYU60TBW2", {'entities': [(33, 52, 'TRUCK_LOCATION')]}),
    ("Happy Friday! Come ha e lunch with us at Virginia Ave and 20th St NW from 11:30am to 2pm. 🤤 #arepas #patacones… https://t.co/AgbiimSwmG", {'entities': [(41, 68, 'TRUCK_LOCATION')]}),
    ("Find us by Union Station today from 11am to 1:30pm! See you at lunchtime! 🤗 #arepas #patacones #cachapas… https://t.co/m0RnNakUfN", {'entities': [(11, 24, 'TRUCK_LOCATION')]}),
    ("Happy humpday! We are at L St and 18th St NW from 11am to 2pm. 😋 see you soon! #arepas #patacones #venezuelanfood… https://t.co/zdqlNAdmHx", {'entities': [(25, 44, 'TRUCK_LOCATION')]}),
    ("Come have lunch with us at L’Enfant Plaza Station from 11:30am to 2pm. 🤤 #arepas #patacones #venezuelanfood… https://t.co/ncYg97TWhn", {'entities': [(27, 49, 'TRUCK_LOCATION')]}),
    ("Happy Friday! Find us at L St and 19th St NW from 11:30 am to 2pm. #arepas #patacones #venezuelanfood #foodtruck… https://t.co/mHSgLR8vFD", {'entities': [(25, 44, 'TRUCK_LOCATION')]}),
    ("Come find us by Union Station from 11:30am to 2pm. See you at lunchtime 🤤 #arepas #patacones #venezuelanfood… https://t.co/mgtXfhQF9z", {'entities': [(16, 29, 'TRUCK_LOCATION')]}),
    ("Happy Friday! We are at Virginia Ave and 20th St NW from 11am to 2pm. See you soon 😋 #arepas #patacones… https://t.co/rdiOS2M8FD", {'entities': [(24, 51, 'TRUCK_LOCATION')]}),
    ("Come find us by Union Station today from 11:15am to 2pm 🤤 #arepas #patacones #empanadas #venezuelanfood #foodtruck… https://t.co/loxNI3jDYw", {'entities': [(16, 29, 'TRUCK_LOCATION')]}),
    ("Happy humpday! Come have lunch with us at L St and 19th St NW from 11:15am to 2pm. See you soon 😋 #arepas… https://t.co/uIc90Wi5R4", {'entities': [(42, 61, 'TRUCK_LOCATION')]}),
    ("Come have lunch with us at L’Enfant Plaza Station from 11:30am to 2pm. #arepas #patacones #venezuelanfood… https://t.co/rHlc8dBTq0", {'entities': [(27, 49, 'TRUCK_LOCATION')]}),
    ("RT @Mahou_DC: Mahou Session IPA on tap now @ArepaZone! #beer #cerveza https://t.co/bU42scrCT2", {'entities': []}),
    ("RT @hylandwx: This Patacón from @ArepaZone is ginormous, but oh so tasty 😋 @UnionMarketDC https://t.co/fMvJcgHU4n", {'entities': []}),
    ("RT @isalara: Recogiendo un pan de jamón! 😛 (at @ArepaZone in Washington, DC) https://t.co/AwgQw1JKo7", {'entities': []}),
    ("RT @renerincon: @porlagoma @jesusalemarin @ArepaZone Si M&amp;M fue muy grato ver a ‘Eterna Juventud’, muy buenos recuerdos de Venevisión y Tel…", {'entities': []}),
    ("RT @porlagoma: Alegra tanto ver a los venezolanos que tienen éxito con sus emprendimientos en Estados Unidos, como mis amigos queridos de @…", {'entities': []}),
    ("RT @LizarazNava: @porlagoma @ArepaZone La mejor arepa que he disfrutado en mi vida. Ricas!", {'entities': []}),
    ("RT @CapHarvestDC: Make your taste buds dance this Friday by picking up one of @ArepaZone's famous arepas for lunch! Some of their many opti…", {'entities': []}),
    ("RT @cecasanovap: Juego del DC United:  ¿Los cánticos? En español.  ¿La comida? La gente de @ArepaZone tiene a medio estadio comiendo arep…", {'entities': []}),
    ("RT @PopeDupontCircl: If you are looking for lunch in Sunday-desolate downtown DC, @ArepaZone is a great option on 14th https://t.co/vhFucNu…", {'entities': [(114, 118, 'TRUCK_LOCATION')]}),
    ("RT @freedomlovererh: Missed @ArepaZone so much when I was away! so glad to be back :) https://t.co/eanmDvOnUa", {'entities': []}),
    ("RT @SmorgasburgDC: If you haven't grabbed a tostones trio from @arepazone, what are you waiting for? Referred to as a patacón, it's a mouth…", {'entities': []}),
    ("RT @AllThingsGo: The Fall Classic food lineup is here! Let us know what eats you’re most excited for in the replies 🍔 #ATGFallClassic http…", {'entities': []}),
    ("RT @Amused_Jade: Chicha de arroz, patacon con Pollo, and cachapas con carne #food #foodpics #foodie #dcfoodie @arepazone https://t.co/QTeH…", {'entities': []}),
    ("RT @tolimolidc: Thank you for including us, @Eater_DC ! Love to see your friends @ArepaZone x Kuya Ja's Lechon Belly, and more on the list…", {'entities': []}),
    ("RT @RobertoNasser: @luciovilla @ArepaZone for awesome Venezuelan food!", {'entities': []}),
    ("RT @NaniaWTOP: Everything we do, we’ve made it a macro version of our family’s recipes … Just calling the matriarchs in both of our familie…", {'entities': []}),
    ("RT @byamichelle: Still regretting the day my Venezuelan friend introduced me to the @ArepaZone around the corner. So delicious and so impos…", {'entities': []}),
    ("Laissez les bon temps rouler 🎉 Get your king cake doughnuts, baby not included this #mardigras. Available in DC and… https://t.co/dzs6PerpQa", {'entities': []}),
    ("We’re at Farragut Square for lunch today DC! Catch us from 11:30-1 😎", {'entities': [(9, 24, 'TRUCK_LOCATION')]}),
    ("The perfect cheddar biscuit &amp; fried chicken-what more could you want in a breakfast? 📸: @lindakuehl #astrodoughnuts https://t.co/S4PQdpPRdG", {'entities': []}),
    ("Good morning DC! Catch us at L’Enfant Plaza from 11:30-1pm today 😋", {'entities': [(29, 43, 'TRUCK_LOCATION')]}),
    ("Returning to work after a long weekend bites-luckily our chocolate covered strawberry doughnuts taste pretty great… https://t.co/JBGiZveUD3", {'entities': []}),
    ("We know it might not feel like summer outside, but one bite of our Key Lime doughnut and it's suddenly sunny &amp; 75 😎… https://t.co/kCerlKvLr9", {'entities': []}),
    ("DC: the truck is at Farragut today from 11:30 to 1 🤘🏻", {'entities': [(20, 28, 'TRUCK_LOCATION')]}),
    ("Hey, LA! Catch the Astro Truck in today from 11-2 in Playa Del Rey! https://t.co/fT83xI7E4D", {'entities': []}),
    ("Have you ordered your #Valentines yet 💘? Surprise your loved ones with a mini box of these beauties via the link in… https://t.co/79VwnvEVWK", {'entities': []}),
    ("We've got our 👀 on the prize today//📸:@fooodmuncher #astrodoughnuts https://t.co/w74xL21y4M", {'entities': []}),
    ("Union Station friends! Find our truck today from 11:30-1:00. See you soon!", {'entities': [(0, 13, 'TRUCK_LOCATION')]}),
    ("Nothing says 'I Love You' quite like a box of doughnuts 💘 Share a box with that special someone or at your Galentin… https://t.co/V3CNYQECZj", {'entities': []}),
    ("NOMA friends, we’ll see you on the truck today from 11:30 to 1:00. Happy Friday 🙌", {'entities': []}),
    ("The perfect lunch doesn't exist....oh wait 😎 Pre-order yours at https://t.co/6yG5Eyqf7V 📸: @thejenchase https://t.co/8mgodtHUky", {'entities': []}),
    ("Our love language is doughnuts 💘 🍩: Blood Orange Mimosa with orange-champagne glaze, chocolate drizzle &amp; gold spri… https://t.co/kHQZlu5gOX", {'entities': []}),
    ("Say good morning to Key Lime Pie, Blood Orange Mimosa, Tiramisu &amp; Chocolate Covered Strawberry, available all Febru… https://t.co/g4Kw6qO2TY", {'entities': []}),
    ("Celebrating #FryDay in NOMA this morning! Catch the truck from 11:30-1", {'entities': []}),
    ("We’ll be at L’Enfant Plaza today from 11:30-1:00. See you soon!", {'entities': [(12, 26, 'TRUCK_LOCATION')]}),
    ("RT @DCSLIDERSTRUCK: Say yes to jobs &amp; city revenue &amp; pass complete food truck ordinance @TimLovain #AlexandriaHeartsFoodTrucks 🍔🍔", {'entities': []}),
    ("hi everyone looks like we are taking off for a week vacation wilbe back soon", {'entities': []}),
    ("http://t.co/ffFrNASthI", {'entities': []}),
    ("RT @TopDogTruck: @Partytrucks thanks for lunch.  I like the new falafel recipe.", {'entities': []}),
    ("RT @TopDogTruck: @Partytrucks thanks for lunch yesterday.  The chicken was delicious.", {'entities': []}),
    ("RT @richcadieux: @RestonPatch View from my front door on Barrel Cooper Court http://t.co/u3UJjixo", {'entities': [(57, 76, 'TRUCK_LOCATION')]}),
    ("RT @CarisSevern: @RestonPatch You can tell it's not Reston, though - the phone-pole thingie... http://t.co/ZQ6fp2gS", {'entities': []}),
    ("RT @KC_Kreative: Thanks @PartyTrucks (ATIP) and @Scoops2u for a super tasty lunch today. Nothing like a gyro and 'chipwich' to fill you up!", {'entities': []}),
    ("Serving at @ResidenceInn Largo - 1330 Caraway Court  Largo From 5:30PM-8:30PM EDT http://t.co/lA7xharyp6", {'entities': [(11, 58, 'TRUCK_LOCATION')]}),
    ("At navy yard ready to open", {'entities': [(3, 12, 'TRUCK_LOCATION')]}),
    ("Ready to serve at friendship heights", {'entities': [(18, 36, 'TRUCK_LOCATION')]}),
    ("Ready to serve our Delicious angus bulgogi at friendship heights", {'entities': [(46, 64, 'TRUCK_LOCATION')]}),
    ("We are here at navy yard with angus aeye round bulgogi and fusion tacos", {'entities': [(15, 24, 'TRUCK_LOCATION')]}),
    ("We here at Virginia ave folks", {'entities': [(11, 23, 'TRUCK_LOCATION')]}),
    ("Friendship heights", {'entities': [(0, 18, 'TRUCK_LOCATION')]}),
    ("We are at lenfant plaza serving our delicious bulgogi, fusion tacos and spicy pork subs", {'entities': [(10, 23, 'TRUCK_LOCATION')]}),
    ("Serving at @ResidenceInn Largo - 1330 Caraway Court  Largo From 5:30PM-8:30PM EDT http://t.co/lA7xharyp6", {'entities': [(11, 58, 'TRUCK_LOCATION')]}),
    ("Navy Yard on this rainy Friday!", {'entities': [(0, 9, 'TRUCK_LOCATION')]}),
    ("Good morning! We are at the State Dept on Virginia ave &amp; 20th! Look for the red truck :)", {'entities': [(24, 65, 'TRUCK_LOCATION')]}),
    ("No parking at Friendship Heights.. We'll be back tomorrow!", {'entities': [(14, 32, 'TRUCK_LOCATION')]}),
    ("Sorry everyone! Change of plans.. Heading to Friendship Heights. We'll be back to State Dept next Wed.", {'entities': [(45, 63, 'TRUCK_LOCATION')]}),
    ("State Department (Virginia Ave) today!", {'entities': [(0, 31, 'TRUCK_LOCATION')]}),
    ("We are at 20th and L St today next to Wells Fargo!", {'entities': [(10, 23, 'TRUCK_LOCATION')]}),
    ("Navy Yard today! Windows up in 15mins!", {'entities': [(0, 9, 'TRUCK_LOCATION')]}),
    ("Happy Friday! Union Station today!", {'entities': [(14, 27, 'TRUCK_LOCATION')]}),
    ("Friendship Heights today! @FeedFHeights @MazzaGallerieDC", {'entities': [(0, 18, 'TRUCK_LOCATION')]}),
    ("#arlington we're rocking long bridge park today. Come check us out for some fish tacos on a hot day.", {'entities': [(25, 41, 'TRUCK_LOCATION')]}),
    ("Thx @TommyWells for standing up for food trucks!", {'entities': []}),
    ("Thanks @VincentOrangeDC for putting forward better food truck regs!", {'entities': []}),
    ("Getting ready for the rest of the week. See you all soon.", {'entities': []}),
    ("Thank you @TommyWells for your strong support for our local food trucks &amp; for your amendment!", {'entities': []}),
    ("#CrystalCity we'll be serving up warm Cuban sandwiches and cold drinks. Come check us out.", {'entities': [(0, 12, 'TRUCK_LOCATION')]}),
    ("#ballston, balstatonions get ready for the cubanators!!", {'entities': [(0, 9, 'TRUCK_LOCATION')]}),
    ("Gotta take a day off, Tour de Fat was too much fun. See you tomorrow.", {'entities': []}),
    ("#tour de fat today. Come down to Yards park and try your favorite Cuban speciality paired with New Belgium beer.", {'entities': [(33, 43, 'TRUCK_LOCATION')]}),
    ("Council Committee votes to reject proposed regs! THANK YOU @VincentOrangeDC @JimGrahamWard1 @GrossoAtLarge @CMYMA @marycheh!", {'entities': []}),
    ("#rossyln, uh oh rosslynators, watch out here comes the Cubanator. 'Get to the choppa'", {'entities': [(0, 8, 'TRUCK_LOCATION')]}),
    ("What's better than fresh Cuban food? Cuban food with a new Belgium beer! See us this weekend at the tour de fat.", {'entities': []}),
    ("#crystal city, don't forget about the tres leche cake!!!", {'entities': [(0, 13, 'TRUCK_LOCATION')]}),
    ("Everyone come see us this weekend at the Tour de Fat to try our specialities paired with different beers. Suggestions?", {'entities': []}),
    ("#arlington courthouse, no signs of rain come try a delicious Cuban!!!", {'entities': [(0, 21, 'TRUCK_LOCATION')]}),
    ("#arlington court house, we will have Cubans and burritos ready to go from 11-2 so if its raining don't worry it will only be just a second", {'entities': [(0, 22, 'TRUCK_LOCATION')]}),
    ("#Rosslyn, don't worry be happy a lo Cubano is here.", {'entities': [(0, 8, 'TRUCK_LOCATION')]}),
    ("our new schedule, mon- rosslyn,tues-Arlington court house, wed-crystal city,Thursday-ballston, fri-rosslyn", {'entities': [(23, 30, 'TRUCK_LOCATION')]}),
    ("'@StationCDRKelly: Day 121. The #Nile at night is like a jewel. Good night from @Space_Station! #YearInSpace http://t.co/L17WDcvk14'MY PEEPS", {'entities': []}),
    ("RT @StationCDRKelly: Day 121. The #Nile at night is like a jewel. Good night from @Space_Station! #YearInSpace http://t.co/T6TTkVyiRw", {'entities': []}),
    ("'@MrTerrificPants: Omg. Why do we put cheese on EVERYTHING?!?' Because it makes it Pretty...", {'entities': []}),
    ("RT @CapitolRvrFront: Packing ur #FridayNightConcert picnic? Many #CapitolRiverfront options + @Agua301WDC @BabasBigBite @bigcheesetruck! ht…", {'entities': []}),
    ("Please help this child if you can. Check it out  http://t.co/kiFxsXkMNh", {'entities': []}),
    ("RT @timelesstrendsb: So excited to have Baba's Big Bite joining us this Saturday for our grand opening in Aldie! Yum yum yum! http://t.co/v…", {'entities': []}),
    ("RT @BallstonBID: #CourageWall coming to #Ballston tomorrow! Check it out and make an affirmation at Welburn Square starting at 4pm http://t…", {'entities': [(100, 114, 'TRUCK_LOCATION')]}),
    ("Whats up Rosslyn Baba's Is curbside flipping some Deliciousness.🍔 Come by &amp; Grab a Bite.", {'entities': []}),
    ("Whats up 20th &amp; L st Babas is Curbside serving up some Deliciousness. Its been too long...", {'entities': [(9, 24, 'TRUCK_LOCATION')]}),
    ("'@burgerdays: Burger Days Rated Rookie.  https://t.co/W8yDy3QWGX' LIKE AH BOSS", {'entities': []}),
    ("RT @burgerdays: Burger Days Rated Rookie.  https://t.co/c96EyuWViY", {'entities': []}),
    ("We're parked in front of @ABC7News", {'entities': []}),
    ("Whats up Rosslyn Baba's Is curbside serving up some Deliciousness. Its been too long", {'entities': []}),
    ("RT @MensHumor: #math http://t.co/jw5l0DAI6q", {'entities': []}),
    ("Wishing you, your family and friends very Happy Holidays and Happy and wonderful New Year!!! #happyholidays… https://t.co/EBAtQg8CAB", {'entities': []}),
    ("RT @7LocksBrewing: @balkaniktaste is here and we have The Walkaways playing from 7:30-10pm with their friends Wes Tucker and the Skillets a…", {'entities': []}),
    ("Finds us today at @7LocksBrewing. Window open 4:30pm-7:30pm. Join us for last time this year and grab delicious… https://t.co/D5ZqYadldn", {'entities': []}),
    ("RT @7LocksBrewing: #FoodTrucks: We have @TrippyTacos240 tomorrow Dec. 19 and @balkaniktaste Saturday, Dec. 21! https://t.co/mflMJyYk50", {'entities': []}),
    ("Find us today at 15400 Calhoun Dr, Rockville. Window open 11am-2pm. #balkanfood #balkanfoodtruck #kyufte… https://t.co/vRMFXlvJ1T", {'entities': [(17, 44, 'TRUCK_LOCATION')]}),
    ("RT @curbsidekitchn: Catch @balkaniktaste tomorrow for Lunch at 15400 Calhoun Dr, Rockville Deliciousness brought to you by @curbsidekitchn…", {'entities': [(63, 90, 'TRUCK_LOCATION')]}),
    ("Find us today at Windridge winery, Darnestown, MD Window open 1pm-6pm. #balkantruck #balkanfood #kyufte… https://t.co/aFw2bzfY8J", {'entities': [(17, 49, 'TRUCK_LOCATION')]}),
    ("Find us today at @7LocksBrewing for delicious Balkan Grill and good local beer. Window open 4:30pm-8pm.… https://t.co/a1SasnEyjg", {'entities': []}),
    ("Wish you very happy and blessed Thanksgiving! #thanksgiving #holiday #family #familytime #turkey #balkanfoodtruck… https://t.co/1I9LIOjAc6", {'entities': []}),
    ("Find us today at @TrueRespite in Rockville. Window open 4pm-8pm. #balkanfood #balkanfoodtruck #pljeskavica #kyufte… https://t.co/Pdf9q2r8Uq", {'entities': []}),
    ("Tonight we will be serving dinner at @mallorysquareapts in Rockville. Window open 5pm-8pm. See you there!… https://t.co/FuzkPeefpw", {'entities': [(37, 68, 'TRUCK_LOCATION')]}),
    ("Serving lunch today at 6701 Democracy blvd, Bethesda. Window open 11am-2pm. #bethesda #balkanfoodtruck #balkanfood… https://t.co/sFXME5Ggj5", {'entities': [(23, 52, 'TRUCK_LOCATION')]})
]
# Loop for 10 iterations
for itn in range(10):
    # Shuffle the training data
    random.shuffle(TRAINING_DATA)
    losses = {}
    # Batch the examples and iterate over them
    for batch in spacy.util.minibatch(TRAINING_DATA, size=2):
        texts = [text for text, entities in batch]
        annotations = [entities for text, entities in batch]
        # Update the model
        nlp.update(texts, annotations, losses=losses)
        print(losses)

nlp.to_disk("./model")
