// DATA
// WHEN STARTING APP UP FIRST THING U DO IS GET THE REGION ID BY ITS NAME
// THEN IN THE FUTURE YOU CAN USE THAT REGION ID TO GET THE DATA OF ALL THE VENDORS


export const RECIEVE_REGION_DATA = 'RECIEVE_REGION_ID'
export const FETCH_REGION_DATA = 'FETCH_REGION_DATA'

export const RECIEVE_VENDOR_PROFILE = 'RECIEVE_VENDOR_PROFILE'
export const POST_VENDOR_COMMENT = 'POST_VENDOR_COMMENT'