export const RECIEVE_REGION_DATA = 'RECIEVE_REGION_ID'
export const FETCH_REGION_DATA = 'FETCH_REGION_DATA'

export const RECIEVE_VENDOR_PROFILE = 'RECIEVE_VENDOR_PROFILE'
export const FETCH_VENDOR_DATA = 'FETCH_VENDOR_DATA'

export const RECIEVE_ALL_VENDORS = 'RECIEVE_ALL_VENDORS'
export const FETCH_ALL_VENDORS = 'FETCH_ALL_VENDORS'

export const POST_VENDOR_COMMENT = 'POST_VENDOR_COMMENT'