const {
  REACT_APP_VENDOR_API,
  REACT_APP_GOOGLE_MAP_API_KEY
  } = process.env;

const VENDOR_API = REACT_APP_VENDOR_API;
const GOOGLE_MAP_API_KEY= REACT_APP_GOOGLE_MAP_API_KEY;

export {
    VENDOR_API,
    GOOGLE_MAP_API_KEY
}